// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package tests

//go:generate minimock -i github.com/gojuno/minimock/v3/tests.formatterAlias -o formatter_alias_mock.go -n FormatterAliasMock -p tests

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// FormatterAliasMock implements formatterAlias
type FormatterAliasMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcFormat          func(s1 string, p1 ...interface{}) (s2 string)
	funcFormatOrigin    string
	inspectFuncFormat   func(s1 string, p1 ...interface{})
	afterFormatCounter  uint64
	beforeFormatCounter uint64
	FormatMock          mFormatterAliasMockFormat
}

// NewFormatterAliasMock returns a mock for formatterAlias
func NewFormatterAliasMock(t minimock.Tester) *FormatterAliasMock {
	m := &FormatterAliasMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.FormatMock = mFormatterAliasMockFormat{mock: m}
	m.FormatMock.callArgs = []*FormatterAliasMockFormatParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mFormatterAliasMockFormat struct {
	optional           bool
	mock               *FormatterAliasMock
	defaultExpectation *FormatterAliasMockFormatExpectation
	expectations       []*FormatterAliasMockFormatExpectation

	callArgs []*FormatterAliasMockFormatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FormatterAliasMockFormatExpectation specifies expectation struct of the formatterAlias.Format
type FormatterAliasMockFormatExpectation struct {
	mock               *FormatterAliasMock
	params             *FormatterAliasMockFormatParams
	paramPtrs          *FormatterAliasMockFormatParamPtrs
	expectationOrigins FormatterAliasMockFormatExpectationOrigins
	results            *FormatterAliasMockFormatResults
	returnOrigin       string
	Counter            uint64
}

// FormatterAliasMockFormatParams contains parameters of the formatterAlias.Format
type FormatterAliasMockFormatParams struct {
	s1 string
	p1 []interface{}
}

// FormatterAliasMockFormatParamPtrs contains pointers to parameters of the formatterAlias.Format
type FormatterAliasMockFormatParamPtrs struct {
	s1 *string
	p1 *[]interface{}
}

// FormatterAliasMockFormatResults contains results of the formatterAlias.Format
type FormatterAliasMockFormatResults struct {
	s2 string
}

// FormatterAliasMockFormatOrigins contains origins of expectations of the formatterAlias.Format
type FormatterAliasMockFormatExpectationOrigins struct {
	origin   string
	originS1 string
	originP1 string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFormat *mFormatterAliasMockFormat) Optional() *mFormatterAliasMockFormat {
	mmFormat.optional = true
	return mmFormat
}

// Expect sets up expected params for formatterAlias.Format
func (mmFormat *mFormatterAliasMockFormat) Expect(s1 string, p1 ...interface{}) *mFormatterAliasMockFormat {
	if mmFormat.mock.funcFormat != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Set")
	}

	if mmFormat.defaultExpectation == nil {
		mmFormat.defaultExpectation = &FormatterAliasMockFormatExpectation{}
	}

	if mmFormat.defaultExpectation.paramPtrs != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by ExpectParams functions")
	}

	mmFormat.defaultExpectation.params = &FormatterAliasMockFormatParams{s1, p1}
	mmFormat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFormat.expectations {
		if minimock.Equal(e.params, mmFormat.defaultExpectation.params) {
			mmFormat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFormat.defaultExpectation.params)
		}
	}

	return mmFormat
}

// ExpectS1Param1 sets up expected param s1 for formatterAlias.Format
func (mmFormat *mFormatterAliasMockFormat) ExpectS1Param1(s1 string) *mFormatterAliasMockFormat {
	if mmFormat.mock.funcFormat != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Set")
	}

	if mmFormat.defaultExpectation == nil {
		mmFormat.defaultExpectation = &FormatterAliasMockFormatExpectation{}
	}

	if mmFormat.defaultExpectation.params != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Expect")
	}

	if mmFormat.defaultExpectation.paramPtrs == nil {
		mmFormat.defaultExpectation.paramPtrs = &FormatterAliasMockFormatParamPtrs{}
	}
	mmFormat.defaultExpectation.paramPtrs.s1 = &s1
	mmFormat.defaultExpectation.expectationOrigins.originS1 = minimock.CallerInfo(1)

	return mmFormat
}

// ExpectP1Param2 sets up expected param p1 for formatterAlias.Format
func (mmFormat *mFormatterAliasMockFormat) ExpectP1Param2(p1 ...interface{}) *mFormatterAliasMockFormat {
	if mmFormat.mock.funcFormat != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Set")
	}

	if mmFormat.defaultExpectation == nil {
		mmFormat.defaultExpectation = &FormatterAliasMockFormatExpectation{}
	}

	if mmFormat.defaultExpectation.params != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Expect")
	}

	if mmFormat.defaultExpectation.paramPtrs == nil {
		mmFormat.defaultExpectation.paramPtrs = &FormatterAliasMockFormatParamPtrs{}
	}
	mmFormat.defaultExpectation.paramPtrs.p1 = &p1
	mmFormat.defaultExpectation.expectationOrigins.originP1 = minimock.CallerInfo(1)

	return mmFormat
}

// Inspect accepts an inspector function that has same arguments as the formatterAlias.Format
func (mmFormat *mFormatterAliasMockFormat) Inspect(f func(s1 string, p1 ...interface{})) *mFormatterAliasMockFormat {
	if mmFormat.mock.inspectFuncFormat != nil {
		mmFormat.mock.t.Fatalf("Inspect function is already set for FormatterAliasMock.Format")
	}

	mmFormat.mock.inspectFuncFormat = f

	return mmFormat
}

// Return sets up results that will be returned by formatterAlias.Format
func (mmFormat *mFormatterAliasMockFormat) Return(s2 string) *FormatterAliasMock {
	if mmFormat.mock.funcFormat != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Set")
	}

	if mmFormat.defaultExpectation == nil {
		mmFormat.defaultExpectation = &FormatterAliasMockFormatExpectation{mock: mmFormat.mock}
	}
	mmFormat.defaultExpectation.results = &FormatterAliasMockFormatResults{s2}
	mmFormat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFormat.mock
}

// Set uses given function f to mock the formatterAlias.Format method
func (mmFormat *mFormatterAliasMockFormat) Set(f func(s1 string, p1 ...interface{}) (s2 string)) *FormatterAliasMock {
	if mmFormat.defaultExpectation != nil {
		mmFormat.mock.t.Fatalf("Default expectation is already set for the formatterAlias.Format method")
	}

	if len(mmFormat.expectations) > 0 {
		mmFormat.mock.t.Fatalf("Some expectations are already set for the formatterAlias.Format method")
	}

	mmFormat.mock.funcFormat = f
	mmFormat.mock.funcFormatOrigin = minimock.CallerInfo(1)
	return mmFormat.mock
}

// When sets expectation for the formatterAlias.Format which will trigger the result defined by the following
// Then helper
func (mmFormat *mFormatterAliasMockFormat) When(s1 string, p1 ...interface{}) *FormatterAliasMockFormatExpectation {
	if mmFormat.mock.funcFormat != nil {
		mmFormat.mock.t.Fatalf("FormatterAliasMock.Format mock is already set by Set")
	}

	expectation := &FormatterAliasMockFormatExpectation{
		mock:               mmFormat.mock,
		params:             &FormatterAliasMockFormatParams{s1, p1},
		expectationOrigins: FormatterAliasMockFormatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFormat.expectations = append(mmFormat.expectations, expectation)
	return expectation
}

// Then sets up formatterAlias.Format return parameters for the expectation previously defined by the When method
func (e *FormatterAliasMockFormatExpectation) Then(s2 string) *FormatterAliasMock {
	e.results = &FormatterAliasMockFormatResults{s2}
	return e.mock
}

// Times sets number of times formatterAlias.Format should be invoked
func (mmFormat *mFormatterAliasMockFormat) Times(n uint64) *mFormatterAliasMockFormat {
	if n == 0 {
		mmFormat.mock.t.Fatalf("Times of FormatterAliasMock.Format mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFormat.expectedInvocations, n)
	mmFormat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFormat
}

func (mmFormat *mFormatterAliasMockFormat) invocationsDone() bool {
	if len(mmFormat.expectations) == 0 && mmFormat.defaultExpectation == nil && mmFormat.mock.funcFormat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFormat.mock.afterFormatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFormat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Format implements formatterAlias
func (mmFormat *FormatterAliasMock) Format(s1 string, p1 ...interface{}) (s2 string) {
	mm_atomic.AddUint64(&mmFormat.beforeFormatCounter, 1)
	defer mm_atomic.AddUint64(&mmFormat.afterFormatCounter, 1)

	mmFormat.t.Helper()

	if mmFormat.inspectFuncFormat != nil {
		mmFormat.inspectFuncFormat(s1, p1...)
	}

	mm_params := FormatterAliasMockFormatParams{s1, p1}

	// Record call args
	mmFormat.FormatMock.mutex.Lock()
	mmFormat.FormatMock.callArgs = append(mmFormat.FormatMock.callArgs, &mm_params)
	mmFormat.FormatMock.mutex.Unlock()

	for _, e := range mmFormat.FormatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s2
		}
	}

	if mmFormat.FormatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFormat.FormatMock.defaultExpectation.Counter, 1)
		mm_want := mmFormat.FormatMock.defaultExpectation.params
		mm_want_ptrs := mmFormat.FormatMock.defaultExpectation.paramPtrs

		mm_got := FormatterAliasMockFormatParams{s1, p1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.s1 != nil && !minimock.Equal(*mm_want_ptrs.s1, mm_got.s1) {
				mmFormat.t.Errorf("FormatterAliasMock.Format got unexpected parameter s1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFormat.FormatMock.defaultExpectation.expectationOrigins.originS1, *mm_want_ptrs.s1, mm_got.s1, minimock.Diff(*mm_want_ptrs.s1, mm_got.s1))
			}

			if mm_want_ptrs.p1 != nil && !minimock.Equal(*mm_want_ptrs.p1, mm_got.p1) {
				mmFormat.t.Errorf("FormatterAliasMock.Format got unexpected parameter p1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFormat.FormatMock.defaultExpectation.expectationOrigins.originP1, *mm_want_ptrs.p1, mm_got.p1, minimock.Diff(*mm_want_ptrs.p1, mm_got.p1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFormat.t.Errorf("FormatterAliasMock.Format got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFormat.FormatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFormat.FormatMock.defaultExpectation.results
		if mm_results == nil {
			mmFormat.t.Fatal("No results are set for the FormatterAliasMock.Format")
		}
		return (*mm_results).s2
	}
	if mmFormat.funcFormat != nil {
		return mmFormat.funcFormat(s1, p1...)
	}
	mmFormat.t.Fatalf("Unexpected call to FormatterAliasMock.Format. %v %v", s1, p1)
	return
}

// FormatAfterCounter returns a count of finished FormatterAliasMock.Format invocations
func (mmFormat *FormatterAliasMock) FormatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFormat.afterFormatCounter)
}

// FormatBeforeCounter returns a count of FormatterAliasMock.Format invocations
func (mmFormat *FormatterAliasMock) FormatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFormat.beforeFormatCounter)
}

// Calls returns a list of arguments used in each call to FormatterAliasMock.Format.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFormat *mFormatterAliasMockFormat) Calls() []*FormatterAliasMockFormatParams {
	mmFormat.mutex.RLock()

	argCopy := make([]*FormatterAliasMockFormatParams, len(mmFormat.callArgs))
	copy(argCopy, mmFormat.callArgs)

	mmFormat.mutex.RUnlock()

	return argCopy
}

// MinimockFormatDone returns true if the count of the Format invocations corresponds
// the number of defined expectations
func (m *FormatterAliasMock) MinimockFormatDone() bool {
	if m.FormatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FormatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FormatMock.invocationsDone()
}

// MinimockFormatInspect logs each unmet expectation
func (m *FormatterAliasMock) MinimockFormatInspect() {
	for _, e := range m.FormatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FormatterAliasMock.Format at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFormatCounter := mm_atomic.LoadUint64(&m.afterFormatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FormatMock.defaultExpectation != nil && afterFormatCounter < 1 {
		if m.FormatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FormatterAliasMock.Format at\n%s", m.FormatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FormatterAliasMock.Format at\n%s with params: %#v", m.FormatMock.defaultExpectation.expectationOrigins.origin, *m.FormatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFormat != nil && afterFormatCounter < 1 {
		m.t.Errorf("Expected call to FormatterAliasMock.Format at\n%s", m.funcFormatOrigin)
	}

	if !m.FormatMock.invocationsDone() && afterFormatCounter > 0 {
		m.t.Errorf("Expected %d calls to FormatterAliasMock.Format at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FormatMock.expectedInvocations), m.FormatMock.expectedInvocationsOrigin, afterFormatCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *FormatterAliasMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockFormatInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *FormatterAliasMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *FormatterAliasMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockFormatDone()
}
